spring:
  application:
    name: Cointoss

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15 minutes
    RefreshTokenExpiration: 604800 # 7 days

quidax:
  secretKey: ${QUIDAX_SECRET_KEY}
  baseUrl: https://app.quidax.io/api/v1
